name: kindness
description: The key to a new (abstract) world.
version: 1.0.0
homepage: https://github.com/modulovalue/kindness
author: Modestas Valauskas <valauskasmodestas+dartpub@gmail.com>

environment:
  sdk: '>=1.0.0 <4.0.0'
