name: kindness
description: The key to a new (abstract) world.
version: 2.0.0
homepage: https://github.com/modulovalue/kindness
author: Modestas Valauskas <valauskasmodestas+dartpub@gmail.com>

environment:
  sdk: '>=2.12.0-29.7.beta <3.0.0'
